"""
调试效率为0的传输问题

分析可能导致传输效率为0的所有情况
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

print("="*70)
print("效率为0的传输 - 可能原因分析")
print("="*70)

print("\n【情况1】没有传输计划（plans为空）")
print("- 原因：网络中没有满足条件的donor-receiver对")
print("- 表现：sent = 0, delivered = 0, efficiency = 0")
print("- 是否正常：✅ 正常（没有传输就是0效率）")
print("- 解决方案：检查网络能量分布，确保有高低能量差异")

print("\n【情况2】Donor能量不足")
print("- 原因：donor.current_energy < total_consumption")
print("- 表现：")
print("  - 传输被统计到sent_total")
print("  - 但donor能量变为负数！")
print("  - receiver可能收到能量，但donor超支")
print("- 是否正常：❌ 异常（不应该允许负能量）")
print("- 潜在问题：")
print("  - donor能量变负会导致后续计算错误")
print("  - 可能触发连锁反应")

print("\n【情况3】所有传输路径效率极低")
print("- 原因：路径效率 < 0.1（被过滤）")
print("- 表现：plans为空，sent = 0")
print("- 是否正常：✅ 正常（低效路径被主动放弃）")
print("- 建议：检查网络拓扑和距离配置")

print("\n【情况4】节点锁定（Duration调度器）")
print("- 原因：所有可用节点都被锁定（正在传输）")
print("- 表现：无可用节点，plans为空")
print("- 是否正常：✅ 正常（节点正在执行长时传输）")
print("- 建议：调整max_duration或增加K值")

print("\n【情况5】统计错误（delivered < 0被修正为0）")
print("- 原因：post_received_total < pre_received_total")
print("- 代码：delivered_total = max(0.0, post_received_total - pre_received_total)")
print("- 可能原因：")
print("  - received_history被意外修改")
print("  - 多线程并发问题")
print("  - 数值精度问题")
print("- 是否正常：❌ 异常（理论上不应该发生）")

print("\n【关键检查点】")
print("-" * 70)

# 检查点1：Donor能量检查
print("\n1. 检查donor能量是否足够")
print("   位置：src/core/network.py 第895行")
print("   当前代码：")
print("   ```python")
print("   donor.current_energy -= total_consumption  # 没有检查！")
print("   ```")
print("   建议修复：")
print("   ```python")
print("   if donor.current_energy < total_consumption:")
print("       print(f'警告：Donor {donor.node_id} 能量不足！')")
print("       print(f'  需要: {total_consumption:.2f}J')")
print("       print(f'  拥有: {donor.current_energy:.2f}J')")
print("       # 跳过此传输或按比例降低")
print("       continue")
print("   ```")

# 检查点2：效率计算
print("\n2. 检查效率计算")
print("   位置：src/scheduling/schedulers.py 第133-136行")
print("   当前逻辑：")
print("   ```python")
print("   if sent > 0:")
print("       efficiency = delivered / sent")
print("   else:")
print("       efficiency = 0.0  # plans为空时")
print("   ```")
print("   建议增强：")
print("   ```python")
print("   if sent > 0:")
print("       efficiency = delivered / sent")
print("       if efficiency == 0:")
print("           print(f'警告：效率为0！sent={sent:.2f}, delivered={delivered:.2f}')")
print("   ```")

# 检查点3：统计计算
print("\n3. 检查统计计算")
print("   位置：src/core/simulation_stats.py 第71行")
print("   当前代码：")
print("   ```python")
print("   delivered_total = max(0.0, post_received_total - pre_received_total)")
print("   ```")
print("   建议增强：")
print("   ```python")
print("   diff = post_received_total - pre_received_total")
print("   if diff < 0:")
print("       print(f'异常：received_history减少了！diff={diff:.2f}')")
print("   delivered_total = max(0.0, diff)")
print("   ```")

print("\n【诊断步骤】")
print("-" * 70)
print("1. 运行仿真时监控日志，查找：")
print("   - 'η=0.00' 或 'η=0' 的传输记录")
print("   - '能量不足' 或负能量警告")
print("   - '效率为0' 的警告信息")
print()
print("2. 检查网络状态：")
print("   - 打印节点能量分布")
print("   - 检查是否有负能量节点")
print("   - 统计锁定节点数量")
print()
print("3. 添加调试输出：")
print("   在 compute_step_stats 中添加：")
print("   ```python")
print("   if sent_total > 0 and delivered_total == 0:")
print("       print(f'警告：有发送但无接收！')")
print("       print(f'  sent_total = {sent_total:.2f}J')")
print("       print(f'  delivered_total = {delivered_total:.2f}J')")
print("       print(f'  plans数量 = {len(plans)}')")
print("   ```")

print("\n【推荐修复方案】")
print("-" * 70)
print("立即修复：添加donor能量检查")
print("位置：src/core/network.py execute_energy_transfer()")
print()
print("修复代码：")
print("```python")
print("# 在第895行之前添加检查")
print("if donor.current_energy < total_consumption:")
print("    print(f'[警告] Donor {donor.node_id} 能量不足，跳过传输')")
print("    print(f'  需要: {total_consumption:.2f}J, 拥有: {donor.current_energy:.2f}J')")
print("    continue  # 跳过此传输")
print("```")

print("\n" + "="*70)
print("建议：运行仿真时观察日志，找出具体是哪种情况")
print("="*70)

